server:
  port: 8080
  servlet:
    context-path: /sportman


spring:
  datasource:
    url: 'jdbc:mysql://localhost:3307/sportman_db'
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true


jwt:
  secretkey: "niKLwtKP9HHYtwxJF4sM2EJYnul+ajhCWEbtgYEnXE06tyfpKeuxgrGie7BiKrDy"


cloudinary:
  apiKey: "aGlS8yvKAnYu1JBtT_hzLvFCunQ"